services:
  bot:
    image: bot_image
    build: ./bot
    container_name: bot-image
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: db_image
    build: ./db
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  db_repl:
    image: db_repl_image
    build: ./db_repl
    container_name: ${DB_REPL_HOST}
    env_file:
      - .env
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

