services:
  bot:
    image: bot_image
    build: ./bot
    container_name: bot-image
    env_file:
      - .env
    depends_on:
      - db
    networks:
      mynet:

  db:
    image: db_image
    build: ./db
    container_name: db-image
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      mynet:
        ipv4_address: ${DB_HOST}

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET}

